### ISSUE TITLE
auth/signin でsetCookie is undefinedエラー

### ISSUE THREAD

**Issue by abeq** [azukiazusa1/elysiajs-taks-api#1]
大変有益な情報の公開およびご提供をありがとうございます。

ElysiaJS のチュートリアルを進めている途中で、auth/index.tsに.post('/auth/signin',...)を追加し、{"username": "john", "password": "password"}を試したところ、```'setCookie' is undefined```のエラーが出ました

```
HTTP/1.1 500 Internal Server Error
{"name":"TypeError","message":"setCookie is not a function. (In 'setCookie(\"token\", token, {\n    httpOnly: !0,\n    maxAge: 900,\n    path: \"/\"\n  })', 'setCookie' is undefined)"}
```

チュートリアルページでは
import {cookie} from '@elysiajs/cookie';
githubのデータに合わせて
import cookie from '@elysiajs/cookie';
にしてみましたが変わりはありませんでした。

何が問題か、アドバイスがいただければとても助かります。
よろしくお願いします。

**Comment by azukiazusa1** [comment]
コメントありがとうございます。

ElysiaJS の最新のバージョンでは、記事を書いた当時とは Cookie を使用する方法が異なっているため、そのことが原因かもしれません :bow:

https://elysiajs.com/patterns/cookie.html#cookie

**Comment by abeq** [comment]
ご回答をありがとうございます。
@elysiajs/cookieのgithubページで下記記載を見つけました。
```
This plugin has been merged into Elysia core and is deprecated, please use [Elysia.cookie](https://elysiajs.com/patterns/cookie.html) instead
```
最新バージョンで動作するように記事を改訂する予定はありますでしょうか？

**Comment by azukiazusa1** [comment]
改訂の予定はございません。

**Comment by abeq** [comment]
>isAuthenticated プラグインにより、user オブジェクトが Context に追加されているため、Handler 関数の引数から user オブジェクトを取得できます

とのことですが、IDE (WebStrom)では```Property 'user' does not exist on type...```のエラーが表示され、実際にbeforeHandle内の関数の引数userが無いようでUnauthorizedになってしまいます。
HttpieでHeaderにCookieを含めて実行してもUnauthorizedになります。
このあたりも現バージョンでの非互換があるのでしょうか？

cookieの方は引数にsetCookieの代わりにcookie:{auth}のように設定し、authで取り出しています。こちらはこれで正常に動作しているように見えます。

ここがクリアになればひととおり動作するので、アドバイスをいただけると大変ありがたく思います。
よろしくお願いします。

**Comment by abeq** [comment]
isAuthenticated.ts のderiveの第1引数として```{as:'scoped'}```を付け加えたところ正常に動作するようになりました。

**Comment by azukiazusa1** [comment]
よかったです 👍
